easy_admin:
    site_name: 'Administracion Mangaka'
    design:
        brand_color: '#f00000'
        assets:
            favicon: '/assets/backend/favicon.png'
    entities:
        Manga:
            class: App\Entity\Manga
            label: 'Mangas'
            list:
                title: "Lista de %%entity_label%%"
                max_results: 30
                fields:
                    - 'Nombre'
                    - { property: 'Portada', type: 'image', base_path: '%media%' }
                    - 'Autor'
                    - 'Descripcion'
                    - 'Capitulos'
                    - 'favoritos'
            form:
                fields:
                    - 'Nombre'
                    - { property: 'Portada', type: 'image', base_path: '%media%' }
                    - 'Autor'
                    - 'Descripcion'
                    - 'Capitulos'
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
        Categoria:
            class: App\Entity\Categoria
        Capitulo:
            class: App\Entity\Capitulo
            form:
                fields:
                    - 'Nombre'
                    - 'Manga'
                    - 'paginas'
        Pagina:
            class: App\Entity\Pagina
        Favoritos:
            class: App\Entity\Favoritos
        Usuarios:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'roles' }
            form:
                fields:
                    - { property: 'email', label: 'Email' }
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                          expanded: true
                          multiple: true
                          choices: { Administrator: 'ROLE_ADMIN' }
                    - { property: 'password', label: 'Password' }
        MediaObject:
            class: App\Entity\MediaObject
            list:
                max_results: 15

            form:
                fields:
                    - { property: 'file', type: 'vich_image'}
