easy_admin:

    site_name: 'Administracion Mangaka Studio'
    design:
        menu:
            - { entity: 'Manga', label: 'Manga', icon: 'book' }
            - { entity: 'Categoria', label: 'Categoria', icon: 'fas fa-atom' }
            - { entity: 'Capitulo', label: 'Capitulo', icon: 'fas fa-copy' }
            - { entity: 'Pagina', label: 'Pagina', icon: 'fas fa-file' }
            - { entity: 'Usuarios', label: 'Usuarios', icon: 'user' }
            - { entity: 'Favoritos', label: 'Favoritos', icon: 'fas fa-heart' }
            - { entity: 'MediaObject', label: 'MediaObject', icon: 'image' }
            - { entity: 'MarcaPaginas', label: 'MarcaPaginas', icon: 'fas fa-bookmark' }
        brand_color: '#f00000'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
    entities:
        Manga:
            class: App\Entity\Manga
            label: 'Manga'
            list:
                max_results: 30
                fields:
                    - 'Nombre'
                    - { property: 'Portada', type: 'image', base_path: '%media%' }
                    - 'Autor'
                    - 'Categoria'
                    - 'Descripcion'
                    - 'Capitulos'
                    - 'favoritos'
            form:
                fields:
                    - 'Nombre'
                    - 'Portada'
                    - 'Autor'
                    - 'Categoria'
                    - 'Descripcion'
                    - 'Capitulos'
            new:
                title: "Crear Manga"
        Categoria:
            class: App\Entity\Categoria
            form:
                fields:
                    - 'Nombre'
                    - 'Decripcion'
        Capitulo:
            class: App\Entity\Capitulo
            form:
                fields:
                    - 'Nombre'
                    - 'Manga'
                    - 'paginas'
        Pagina:
            class: App\Entity\Pagina
        Favoritos:
            class: App\Entity\Favoritos
        Usuarios:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'roles' }
            form:
                fields:
                    - { property: 'email', label: 'Email' }
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                          expanded: true
                          multiple: true
                          choices: { Administrator: 'ROLE_ADMIN' }
                    - { property: 'password', label: 'Password' }
        MediaObject:
            class: App\Entity\MediaObject
            list:
                max_results: 15
            form:
                fields:
                    - { property: 'file', type: 'vich_image'}
        MarcaPaginas:
            class: App\Entity\MarcaPaginas
            list:
                max_results: 15
